# Generated by Django 5.1.6 on 2025-02-21 05:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='book_pdfs/')),
                ('processed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_chapters', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='booksummary.book')),
            ],
        ),
    ]
