# Generated by Django 5.1.6 on 2025-03-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksummary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='compression_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
