# Generated by Django 5.1.6 on 2025-03-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksummary', '0002_migrate_books_to_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookchapters', to='booksummary.book')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booksummary.bookchapter')),
            ],
        ),
        migrations.CreateModel(
            name='BookChapterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('prompt_used', models.TextField()),
                ('compression_ratio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='booksummary.bookchapter')),
            ],
            options={
                'verbose_name_plural': 'BookChapter summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='active_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_chapters', to='booksummary.bookchaptersummary'),
        ),
    ]
