# Generated by Django 5.1.6 on 2025-03-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksummary', '0003_bookchapter_bookchaptersummary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchaptersummary',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booksummary.chapter'),
        ),
        migrations.DeleteModel(
            name='BookChapter',
        ),
        migrations.DeleteModel(
            name='BookChapterSummary',
        ),
    ]
