# Generated by Django 5.1.6 on 2025-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksummary', '0004_remove_bookchaptersummary_chapter_chapter_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.CharField(max_length=50),
        ),
    ]
